# Generated by Django 3.2.7 on 2021-11-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('courseInterest', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
