# Generated by Django 3.2.7 on 2021-11-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiryform',
            old_name='State',
            new_name='state',
        ),
    ]
